version: '3.9'
services:
  database:
    image: mysql:8.0.31
    env_file: ./.env
    restart: unless-stopped
    ports:
      - $MYSQLDB_LOCAL_PORT:$DB_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      # - MYSQL_USER=$MYSQLDB_USER
      # - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
  backend:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=database
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true  
    
  nginx:
    depends_on:
      - database
      - backend
    image: nginx:1.27.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/api-test.crt:/etc/ssl/certs/api-test.crt
      - ./nginx/certs/api-test.key:/etc/ssl/private/api-test.key
